name: femora
description: "Femora - AI Powered Women's Health & Wellness Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  http: ^1.2.2

dependency_overrides:
  path_provider_android: 2.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
