// GENERATED by ml/cycle_eval.py. Do not edit by hand: rerun the script.
// Source: Fehring et al. 2013, Marquette University, 159 women, 1665 cycles.

class CycleParams {
  final double lengthMean; // average cycle length of all women, days
  final double tau; // her own cycles are worth this many population cycles when averaging
  final double withinSd; // typical spread of one woman's cycle length, days
  final int sdWeight; // her own spread counts like this many cycles of population spread
  final double mensesMean; // average period length, days
  final int mensesWeight; // her own period lengths count like this many population periods
  final int lutealDays; // days from ovulation to the next period (median)
  final double windowZ; // width of the 'expected between' window, in standard deviations

  const CycleParams({
    required this.lengthMean,
    required this.tau,
    required this.withinSd,
    required this.sdWeight,
    required this.mensesMean,
    required this.mensesWeight,
    required this.lutealDays,
    required this.windowZ,
  });
}

const kCycleParams = CycleParams(
  lengthMean: 29.3,
  tau: 1.07,
  withinSd: 3.01,
  sdWeight: 3,
  mensesMean: 5.24,
  mensesWeight: 2,
  lutealDays: 13,
  windowZ: 1.28,
);
